### ISSUE TITLE
Adding Lindsey's samples

### ISSUE THREAD

**Issue by lindsey47** [omarcostahamido/Music47#45]
Please Add Lindsey's samples

**Comment by lindsey47** [comment]
Red Velvet Psycho 1+2+3

**Comment by lindsey47** [comment]
this was fixed by #45

**Comment by omarcostahamido** [comment]
issue here, ok.
now need to create the pull request from your repo fork (lindsey47/music47) into this repo (omarcostahamido/music47).

**Comment by omarcostahamido** [comment]
you don't need to manually close the issue.
It will be closed when I merge your pull request.

**Comment by lindsey47** [comment]
this was fixed by #46
